Enhancement: "Everything is ok" message after retrying

When a recoverable error is encountered, restic displays a warning message
saying it's retrying, like this one:

Save(<data/956b9ced99>) returned error, retrying after 357.131936ms: CreateBlockBlobFromReader: Put https://example.blob.core.windows.net/restic/data/95/956b9ced99...aac: write tcp 192.168.11.18:51620->1.2.3.4:443: write: connection reset by peer

This message can be a little confusing because it seems like there was an
error, but we're not sure if it was actually fixed by retrying.

restic is now displaying a confirmation that the action was successful after retrying:

Save(<data/956b9ced99>) operation successful after 1 retries

https://github.com/restic/restic/issues/1734
https://github.com/restic/restic/pull/2661
